feat: add menus handling system
menus now are stored in $MENUS_DIR ( by default), and menu-handler script is simply used to run them.

diff --git a/.local/bin/menu-handler b/.local/bin/menu-handler
--- a/.local/bin/menu-handler
+++ b/.local/bin/menu-handler
@@ -2,16 +2,13 @@
 
 set -eu
 
-action="${1:-$(printf "input\nrecents\nbookmarks\npass\npass-otp\nclipboard\nemojis\nscreenshot\nscreenrec\ndisplay-profiles\nsysact" | menu -p "menu> ")}" || exit 1
-case "$action" in
-	input | recents | bookmarks | clipboard | emojis | screenshot | screenrec | display-profiles | sysact)
-		exec "menu-$action"
-		;;
-	pass | pass-otp)
-		exec passmenu "${action#*-}"
-		;;
-	*)
-		echo "$(basename "$0"): invalid menu: $action" >&2
-		exit 1
-		;;
-esac
+MENUS_DIR="${MENUS_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/menus}"
+
+menu="${1:-$(find -L "$MENUS_DIR" -type f -executable -printf "%P\n" | menu -p "menu> ")}" || exit 1
+[ -x "$MENUS_DIR/$menu" ] || {
+	echo "$(basename "$0"): invalid menu: $menu" >&2
+	exit 1
+}
+
+[ $# -gt 0 ] && shift
+exec "$MENUS_DIR/$menu" "$@"
