improve scripts

diff --git a/.local/bin/menu-screenshot b/.local/bin/menu-screenshot
--- a/.local/bin/menu-screenshot
+++ b/.local/bin/menu-screenshot
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+set -eu
+
 notify() {
 	notify-send -a "$(basename "$0")" "$@"
 }
@@ -12,10 +14,12 @@ for p in grim slurp wl-copy notify-send xdg-user-dir; do
 done
 
 dir="$(xdg-user-dir PICTURES)/screenshots"
-[ -d "$dir" ] || mkdir -p "$dir" || {
-	notify -u critical "error" "cannot create directory $dir"
-	exit 1
-}
+[ -d "$dir" ] ||
+	mkdir -p "$dir" ||
+	{
+		notify -u critical "error" "cannot create directory $dir"
+		exit 1
+	}
 
 sel="${1:-$(printf "select\nfullscreen\nselect-copy\nfullscreen-copy" | menu -p "$(basename "$0")> ")}"
 out="$dir/$(date "+%Y%m%d-%H%M%S").png"
