feat: improve menu prompts

diff --git a/.local/bin/menu-handler b/.local/bin/menu-handler
--- a/.local/bin/menu-handler
+++ b/.local/bin/menu-handler
@@ -3,12 +3,17 @@
 set -eu
 
 MENUS_DIR="${MENUS_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/menus}"
+export MENU_PROMPT="Menu"
 
-menu="${1:-$(find -L "$MENUS_DIR" -type f -executable -printf "%P\n" | menu -p "menu> ")}" || exit 1
-[ -x "$MENUS_DIR/$menu" ] || {
-	echo "$(basename "$0"): invalid menu: $menu" >&2
+# TODO: remove tail pipe when https://codeberg.org/dnkl/fuzzel/issues/700 is fixed
+menu="${1:-$(menu --nth-delimiter "," --with-nth 2 <"$MENUS_DIR/menus.txt" | tail -1)}" || exit 1
+name="${menu#*,}"
+script="${menu%,*}"
+
+[ -x "$MENUS_DIR/$script" ] || {
+	echo "$(basename "$0"): invalid menu: $name" >&2
 	exit 1
 }
 
 [ $# -gt 0 ] && shift
-exec "$MENUS_DIR/$menu" "$@"
+MENU_PROMPT="$name" exec "$MENUS_DIR/$script" "$@"
