improve error handling

diff --git a/.local/bin/menu-handler b/.local/bin/menu-handler
--- a/.local/bin/menu-handler
+++ b/.local/bin/menu-handler
@@ -31,8 +31,10 @@ case "$action" in
 	bookmark)
 		url="$(getinput "$action")"
 		tag="$(buku --nostdin --stag --np | cut -d "." -f 2 | cut -d " " -f 2 | menu -p "tag> ")" || exit 1
-		buku --nostdin --tacit --np -a "$url" "$tag" >/dev/null 2>&1 ||
+		buku --nostdin --tacit --np -a "$url" "$tag" >/dev/null 2>&1 || {
+			echo "$(basename "$0"): $action: adding '$url' with tag '$tag' failed" >&2
 			notify -u critical "error" "$action: adding '$url' with tag '$tag' failed"
+		}
 		;;
 	list-bookmarks)
 		buku --nostdin -p -f 4 |
@@ -42,7 +44,9 @@ case "$action" in
 			xargs -r buku --nostdin -o
 		;;
 	*)
-		notify "error" "invalid action: $action"
+
+		echo "$(basename "$0"): invalid action: $action" >&2
+		notify -u critical "error" "invalid action: $action"
 		exit 1
 		;;
 esac
diff --git a/.local/bin/menu-screenshot b/.local/bin/menu-screenshot
--- a/.local/bin/menu-screenshot
+++ b/.local/bin/menu-screenshot
@@ -8,20 +8,19 @@ notify() {
 
 for p in grim slurp wl-copy notify-send xdg-user-dir; do
 	command -v "$p" >/dev/null 2>&1 || {
-		notify -u critical "$p not found"
+		echo "$(basename "$0"): $p not found" >&2
 		exit 1
 	}
 done
 
 dir="$(xdg-user-dir PICTURES)/screenshots"
-[ -d "$dir" ] ||
-	mkdir -p "$dir" ||
-	{
-		notify -u critical "error" "cannot create directory $dir"
-		exit 1
-	}
+[ -d "$dir" ] || mkdir -p "$dir" || {
+	echo "$(basename "$0"): cannot create directory $dir" >&2
+	notify -u critical "error" "cannot create directory $dir"
+	exit 1
+}
 
-sel="${1:-$(printf "select\nfullscreen\nselect-copy\nfullscreen-copy" | menu -p "$(basename "$0")> ")}"
+sel="${1:-$(printf "select\nfullscreen\nselect-copy\nfullscreen-copy" | menu -p "$(basename "$0")> ")}" || exit 1
 out="$dir/$(date "+%Y%m%d-%H%M%S").png"
 case "$sel" in
 	select)
