bin/menu-screenshot: send notifications

diff --git a/.local/bin/menu-screenshot b/.local/bin/menu-screenshot
--- a/.local/bin/menu-screenshot
+++ b/.local/bin/menu-screenshot
@@ -9,26 +9,31 @@ for p in grim slurp wl-copy notify-send xdg-user-dir; do
 done
 
 dir="$(xdg-user-dir PICTURES)/screenshots"
-[ -d "$dir" ] || mkdir -p "$dir" || { notify -u critical "cannot create directory $dir"; exit 1; }
+[ -d "$dir" ] || mkdir -p "$dir" || { notify -u critical "error" "cannot create directory $dir"; exit 1; }
 
-action="${1:-$(printf "select\nfullscreen\nselect-copy\nfullscreen-copy" | menu -p "$(basename "$0")> ")}"
-case "$action" in
+sel="${1:-$(printf "select\nfullscreen\nselect-copy\nfullscreen-copy" | menu -p "$(basename "$0")> ")}"
+out="$dir/$(date "+%Y%m%d-%H%M%S").png"
+case "$sel" in
 	select)
 		g="$(slurp -d)" || exit 1
-		grim -g "$g" "$dir/$(date "+%Y%m%d-%H%M%S").png"
+		grim -g "$g" "$out"
+		notify "screenshot" "saved to $out"
 		;;
 	fullscreen)
-		grim "$dir/$(date "+%Y%m%d-%H%M%S").png"
+		grim "$out"
+		notify "screenshot" "saved to $out"
 		;;
 	select-copy)
 		g="$(slurp -d)" || exit 1
 		grim -g "$g" - | wl-copy -t image/png
+		notify "screenshot" "saved to clipboard"
 		;;
 	fullscreen-copy)
 		grim - | wl-copy -t image/png
+		notify "screenshot" "saved to clipboard"
 		;;
 	*)
-		notify -u critical "invalid action: $action"
+		notify -u critical "invalid selection: $sel"
 		exit 1
 	;;
 esac
