bin/notes: add arguments to buku

diff --git a/.local/bin/notes b/.local/bin/notes
--- a/.local/bin/notes
+++ b/.local/bin/notes
@@ -33,7 +33,7 @@ case "$1" in
 		for name in "$NOTESDIR"/*; do
 			urls="$(grep -P -o '(?:https?://|ftp://|news://|mailto:|file://|\bwww\.)[a-zA-Z0-9\-\@;\/?:&=%\$_.+!*\x27,~#]*(\([a-zA-Z0-9\-\@;\/?:&=%\$_.+!*\x27,~#]*\)|[a-zA-Z0-9\-\@;\/?:&=%\$_+*~])+' "$name")"
 			for url in $urls; do
-				buku -a "$url" "$(basename "$0"),$(basename "$name" | cut -d. -f1)" || echo "$(basename "$0"): failed to add ($url) to buku" >&2
+				buku --nostdin --threads 10 -a "$url" "$(basename "$0"),$(basename "$name" | cut -d. -f1)" || echo "$(basename "$0"): failed to add ($url) to buku" >&2
 			done
 		done
 		exit $?
