feat(passmenu): list password fields

diff --git a/.local/bin/passmenu b/.local/bin/passmenu
--- a/.local/bin/passmenu
+++ b/.local/bin/passmenu
@@ -1,38 +1,33 @@
 #!/bin/sh
-# passmenu replacement for Wayland
-# requires pass, wl-copy (wl-clipboard), notify-send (libnotify), and menu script
 
 set -eu
 
-export PASSWORD_STORE_DIR="${PASSWORD_STORE_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/password-store}"
-
 app="$(basename "$0")"
-case "${1:-}" in
-"") ;;
-otp) otp=1 ;;
-*)
-	echo "$app: unknown command: $1" >&2
-	exit 1
-	;;
-esac
 
-export MENU_PROMPT="${MENU_PROMPT:-$app${otp:+ otp}}"
+export MENU_PROMPT="${MENU_PROMPT:-$app}"
+export PASSWORD_STORE_DIR="${PASSWORD_STORE_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/password-store}"
 
 sel="$(
 	find "$PASSWORD_STORE_DIR" -type f -name "*.gpg" -printf "%P\n" |
 		sed 's/\.gpg$//' |
 		menu
 )" || exit 1
-
-pass="$(pass ${otp:+otp} "$sel" | sed 1q)" || {
-	echo "$app: pass${otp:+ otp} command failed" >&2
-	notify-send -a "$app" -u critical error "pass${otp:+ otp} command failed"
-	exit 1
+content="$(pass "$sel")" || {
+	ec=$?
+	echo "$app: pass command failed" >&2
+	notify-send -a "$app" -u critical error "pass command failed"
+	exit $ec
 }
+field="$(
+	echo "$content" |
+		sed "1s/.*/password/;s/otpauth:\/\/.*/otp/;s/^\([^:]*\)\s*:\s*.*/\1/" |
+		menu
+)" || exit $?
+case "$field" in
+password) pass="$(echo "$content" | sed 1q)" ;;
+otp) pass="$(pass otp code "$sel")" ;;
+*) pass="$(echo "$content" | sed -n "s/$field\s\+\?:\s\+\?\(.*\)/\1/p")" ;;
+esac
 
-# TODO: add --sensitive option on new release
-echo "$pass" | wl-copy --type text/plain --foreground --trim-newline
-cliphist delete-query "$pass"
-
-[ "${otp:-0}" -eq 1 ] && type="otp" || type="password"
-notify-send -a "$app" "$sel" "$type copied to clipboard"
+echo "$pass" | wl-copy --sensitive --type text/plain --foreground --trim-newline
+notify-send -a "$app" "$sel" "$field copied to clipboard"
