feat: improve menus
- add menu subcommands for input and slug
- better prompt handling
- more icons

diff --git a/.local/share/menus/screenrec b/.local/share/menus/screenrec
--- a/.local/share/menus/screenrec
+++ b/.local/share/menus/screenrec
@@ -4,15 +4,21 @@
 
 set -eu
 
+export MENU_PROMPT="${MENU_PROMPT:-Screen Recording}"
+
 wfpid="$(pidof -sx wf-recorder 2>/dev/null)" && {
-	sel="${1:-$(printf "stop\ncancel" | menu -p "${MENU_PROMPT:-> }Stop recording? ")}" || exit 1
+	sel="${1:-$(printf " Stop\n Cancel" | menu slug -p "$MENU_PROMPT> Stop recording?")}" || exit 1
 	case "$sel" in
 		stop)
 			while kill -INT "$wfpid" >/dev/null 2>&1; do sleep 0.1; done
 			pkill -RTMIN+8 waybar
 			;;
-		cancel) ;;
-		*) exit 1 ;;
+		cancel)
+			;;
+		*)
+			echo "$(basename "$0"): invalid command: $sel" >&2
+			exit 1
+			;;
 	esac
 	exit 0
 }
@@ -24,13 +30,25 @@ dir="$(xdg-user-dir VIDEOS)/recordings"
 	exit 1
 }
 
-sel="${1:-$(printf "fullscreen\nfullscreen-video-only\nselect\nselect-video-only" | menu)}" || exit 1
+sel="${1:-$(printf " Fullscreen\n Fullscreen (Video Only)\n Select\n Select (Video Only)" | menu slug)}" || exit 1
 case "$sel" in
-	fullscreen) set -- -a ;;
-	fullscreen-video-only) ;;
-	select) set -- -a -g "$(slurp -d)" || exit 1 ;;
-	select-video-only) set -- -g "$(slurp -d)" || exit 1 ;;
-	*) exit 1 ;;
+	fullscreen)
+		set -- -a
+		;;
+	fullscreen-video-only)
+		;;
+	select)
+		g="$(slurp -d)" || exit 1
+		set -- -a -g "$g"
+		;;
+	select-video-only)
+		g="$(slurp -d)" || exit 1
+		set -- -g "$g"
+		;;
+	*)
+		echo "$(basename "$0"): invalid command: $sel" >&2
+		exit 1
+		;;
 esac
 setsid -f wf-recorder "$@" -f "$dir/$(date "+%Y%m%d-%H%M%S").mkv"
 pkill -RTMIN+8 waybar
diff --git a/.local/share/menus/screenshot b/.local/share/menus/screenshot
--- a/.local/share/menus/screenshot
+++ b/.local/share/menus/screenshot
@@ -4,6 +4,8 @@
 
 set -eu
 
+export MENU_PROMPT="${MENU_PROMPT:-Screenshot}"
+
 dir="$(xdg-user-dir PICTURES)/screenshots"
 [ -d "$dir" ] || mkdir -p "$dir" || {
 	echo "$(basename "$0"): cannot create directory $dir" >&2
@@ -11,35 +13,35 @@ dir="$(xdg-user-dir PICTURES)/screenshots"
 	exit 1
 }
 
-sel="${1:-$(printf "select\nfullscreen\nselect-copy\nfullscreen-copy\nselect-edit\nfullscreen-edit" | menu)}" || exit 1
-out="$dir/$(date "+%Y%m%d-%H%M%S").png"
+sel="${1:-$(printf " Select\n Fullscreen" | menu slug)}" || exit 1
 case "$sel" in
+	fullscreen)
+		;;
 	select)
 		g="$(slurp -d)" || exit 1
-		grim -g "$g" "$out"
-		notify-send -a "$(basename "$0")" "screenshot" "saved to $out"
-		;;
-	fullscreen)
-		grim "$out"
-		notify-send -a "$(basename "$0")" "screenshot" "saved to $out"
-		;;
-	select-copy)
-		g="$(slurp -d)" || exit 1
-		grim -g "$g" - | wl-copy -t image/png
-		notify-send -a "$(basename "$0")" "screenshot" "saved to clipboard"
-		;;
-	fullscreen-copy)
-		grim - | wl-copy -t image/png
-		notify-send -a "$(basename "$0")" "screenshot" "saved to clipboard"
-		;;
-	select-edit)
-		g="$(slurp -d)" || exit 1
-		grim -g "$g" -t ppm - | satty -f - -o "$out"
-		;;
-	fullscreen-edit)
-		grim -t ppm - | satty -f - -o "$out"
 		;;
 	*)
+		echo "$(basename "$0"): invalid command: $sel" >&2
+		exit 1
+		;;
+esac
+
+sel="${2:-$(printf " Copy\n Save\n Edit" | menu slug)}" || exit 1
+case "$sel" in
+	copy)
+		grim ${g:+-g "$g"} - | wl-copy -t image/png
+		notify-send -a "$(basename "$0")" "screenshot" "saved to clipboard"
+		;;
+	save)
+		out="$dir/$(date "+%Y%m%d-%H%M%S").png"
+		grim ${g:+-g "$g"} "$out"
+		notify-send -a "$(basename "$0")" "screenshot" "saved to $out"
+		;;
+	edit)
+		grim ${g:+-g "$g"} -t ppm - | satty -f - -o "$out"
+		;;
+	*)
+		echo "$(basename "$0"): invalid subcommand: $sel" >&2
 		exit 1
 		;;
 esac
diff --git a/.local/share/menus/sysact b/.local/share/menus/sysact
--- a/.local/share/menus/sysact
+++ b/.local/share/menus/sysact
@@ -2,12 +2,30 @@
 
 set -eu
 
-case "${1:-$(printf "lock\nexit\nsuspend\nhibernate\nreboot\npoweroff" | menu)}" in
-	lock) loginctl -i lock-session ;;
-	exit) riverctl exit ;;
-	suspend) loginctl -i suspend ;;
-	hibernate) loginctl -i hibernate ;;
-	reboot) loginctl -i reboot ;;
-	poweroff) loginctl -i poweroff ;;
-	*) exit 1 ;;
+export MENU_PROMPT="${MENU_PROMPT:-Power Menu}"
+
+sel="${1:-$(printf " Lock\n Exit\n Suspend\n Hibernate\n Reboot\n Power Off" | menu slug)}" || exit 1
+case "$sel" in
+	lock)
+		loginctl -i lock-session
+		;;
+	exit)
+		riverctl exit
+		;;
+	suspend)
+		loginctl -i suspend
+		;;
+	hibernate)
+		loginctl -i hibernate
+		;;
+	reboot)
+		loginctl -i reboot
+		;;
+	power-off)
+		loginctl -i poweroff
+		;;
+	*)
+		echo "$(basename "$0"): invalid command: $sel" >&2
+		exit 1
+		;;
 esac
